server:
  port: 8084

spring:
  application:
    name: sample-code

  # --- DataSource (MySQL) ---
  datasource:
    url: jdbc:mysql://localhost:3306/sampledbJava?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Tuong2005@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariConnPool

  # --- JPA (MySQL) ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:29092
  # --- Mail (Gmail SMTP) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: monsterminecraft2005@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # --- Servlet (Multipart) ---
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

  main:
    allow-bean-definition-overriding: true

  # --- Redis ---
  redis:
    host: localhost
    port: 6379

  # --- MongoDB (For Audit Logs) ---
  data:
    mongodb:
      uri: mongodb://localhost:27017/sample_audit_db

  # --- JWT Configuration ---
  jwt:
    expiryTime: 86400000  # 24 hours in milliseconds
    secretKey: VGEtQ2FuLVBoYWktQ28tTW90LVNlY3JldEtleS1EdS1EYWktRGUtQmFvLU1hdC1DaG8tVW5nLUR1bmctTmF5LTEyMzQ1Njc4OTA=
    refreshKey: 5ef18408b868427f9891f7de972b4f111dfa196516ae740e00df84c666238dcf=
    resetKey: 5ef18408b868427f9891f7de972b4f111dfa596516a77e0e00df84c666238dcf=

  # --- OpenAPI (Swagger) Configuration ---
  open:
    api:
      title: Sample API
      version: 1.0.0
      description: API documentation for the sample application.
      serverUrl: http://localhost:8084
      serverName: Local Development Server
  
